// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZUzbKIfc8zp0zJ-XJnMXuRRK73QU8_xs',
    appId: '1:679383859673:web:13318349c8442d1d8919c8',
    messagingSenderId: '679383859673',
    projectId: 'farhan-portfolio-web',
    authDomain: 'farhan-portfolio-web.firebaseapp.com',
    storageBucket: 'farhan-portfolio-web.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvXt6xvXXfqlemmrZ9CoTyRo_siU2K_gs',
    appId: '1:679383859673:android:7976bb792dddc0398919c8',
    messagingSenderId: '679383859673',
    projectId: 'farhan-portfolio-web',
    storageBucket: 'farhan-portfolio-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiLLXiQOomkXXBPih5zTxJjwRgb2saKuY',
    appId: '1:679383859673:ios:8c771eac623876438919c8',
    messagingSenderId: '679383859673',
    projectId: 'farhan-portfolio-web',
    storageBucket: 'farhan-portfolio-web.appspot.com',
    iosClientId: '679383859673-9b5668nndkludm4tn33f8uif03tut582.apps.googleusercontent.com',
    iosBundleId: 'farhanferdous.com.farhanFerdous',
  );
}
