// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCigGqKBen5MLNPSJwXmBzcuszqM23n2x4',
    appId: '1:143165373062:web:d1a8459d595081a6a4ef07',
    messagingSenderId: '143165373062',
    projectId: 'farhan-web-personal-portfolio',
    authDomain: 'farhan-web-personal-portfolio.firebaseapp.com',
    storageBucket: 'farhan-web-personal-portfolio.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuwCaL38JjSpd-FVp7b1Vfbca2tvmSV1s',
    appId: '1:143165373062:android:d5508f5531cfed40a4ef07',
    messagingSenderId: '143165373062',
    projectId: 'farhan-web-personal-portfolio',
    storageBucket: 'farhan-web-personal-portfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYSkfkr-8wBUmVsPTExP15jkqxUfEPCW4',
    appId: '1:143165373062:ios:ea1a3194d701b11aa4ef07',
    messagingSenderId: '143165373062',
    projectId: 'farhan-web-personal-portfolio',
    storageBucket: 'farhan-web-personal-portfolio.appspot.com',
    iosClientId: '143165373062-a9muab7gke2ro84rr0tec0m4tfcfi8pt.apps.googleusercontent.com',
    iosBundleId: 'farhanferdous.com.farhanFerdous',
  );
}
